# Generated by Django 5.2.12 on 2026-07-12 12:56

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Maximum outstanding credit allowed for this supplier.', max_digits=16),
        ),
        migrations.AddField(
            model_name='vendor',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='pan',
            field=models.CharField(blank=True, max_length=10, verbose_name='PAN'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.CreateModel(
            name='SupplierAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('BILLING', 'Billing'), ('SHIPPING', 'Shipping'), ('OFFICE', 'Office'), ('FACTORY', 'Factory / Works')], default='OFFICE', max_length=10)),
                ('line1', models.CharField(max_length=255)),
                ('line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('state', models.CharField(blank=True, max_length=120)),
                ('pincode', models.CharField(blank=True, max_length=12)),
                ('country', models.CharField(default='India', max_length=120)),
                ('is_default', models.BooleanField(default=False)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='procurement.vendor')),
            ],
            options={
                'verbose_name_plural': 'supplier addresses',
                'ordering': ['-is_default', 'kind'],
            },
        ),
        migrations.CreateModel(
            name='SupplierBankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=40)),
                ('bank_name', models.CharField(max_length=200)),
                ('branch', models.CharField(blank=True, max_length=200)),
                ('ifsc', models.CharField(blank=True, max_length=15, verbose_name='IFSC')),
                ('is_default', models.BooleanField(default=False)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_accounts', to='procurement.vendor')),
            ],
            options={
                'ordering': ['-is_default', 'bank_name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('designation', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='procurement.vendor')),
            ],
            options={
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SupplierDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('GST', 'GST Certificate'), ('PAN', 'PAN Card'), ('MSME', 'MSME / Udyam'), ('CHEQUE', 'Cancelled Cheque'), ('AGREEMENT', 'Agreement'), ('OTHER', 'Other')], default='OTHER', max_length=12)),
                ('file', models.FileField(upload_to='supplier_docs/')),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='procurement.vendor')),
            ],
            options={
                'ordering': ['kind', 'title'],
            },
        ),
    ]
