# Generated by Django 5.2.12 on 2026-07-12 13:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_vendor_credit_limit_vendor_notes_vendor_pan_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestForQuotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SENT', 'Sent to Suppliers'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=12)),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('response_deadline', models.DateField(blank=True, help_text='Quotations received after this date may be ignored.', null=True)),
                ('terms', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfqs', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rfqs', to='procurement.project')),
                ('requisition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rfqs', to='procurement.purchaserequisition')),
                ('vendors', models.ManyToManyField(blank=True, related_name='rfqs', to='procurement.vendor')),
            ],
            options={
                'verbose_name': 'request for quotation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RFQLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='procurement.material')),
                ('rfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.requestforquotation')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
