# Generated by Django 5.2.12 on 2026-07-12 15:35

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('procurement', '0004_supplierquotation_supplierquotationline_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('document_type', models.CharField(choices=[('PURCHASE_REQUISITION', 'Purchase Requisition'), ('PURCHASE_ORDER', 'Purchase Order'), ('VENDOR_BILL', 'Vendor Bill'), ('PURCHASE_CONTRACT', 'Purchase Contract')], max_length=32)),
                ('level', models.PositiveSmallIntegerField(default=1, help_text='Approval order; level 1 approves first.')),
                ('role_required', models.CharField(help_text='accounts.Role value that may approve this level.', max_length=32)),
                ('min_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Upper bound of the band; blank means no upper limit.', max_digits=16, null=True)),
                ('escalate_after_hours', models.PositiveIntegerField(default=0, help_text='Flag the step as overdue after this many hours (0 = never).')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['document_type', 'level', 'min_amount'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('document_type', models.CharField(choices=[('PURCHASE_REQUISITION', 'Purchase Requisition'), ('PURCHASE_ORDER', 'Purchase Order'), ('VENDOR_BILL', 'Vendor Bill'), ('PURCHASE_CONTRACT', 'Purchase Contract')], max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=10)),
                ('current_level', models.PositiveSmallIntegerField(default=1)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('level', models.PositiveSmallIntegerField()),
                ('role_required', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=10)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('acted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_steps', to=settings.AUTH_USER_MODEL)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='procurement.approvalrequest')),
            ],
            options={
                'ordering': ['level', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['content_type', 'object_id'], name='procurement_content_8e86c0_idx'),
        ),
    ]
