# Generated by Django 5.2.12 on 2026-07-12 15:42

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('procurement', '0005_approvalrule_approvalrequest_approvalstep_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='emailed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='revision',
            field=models.PositiveSmallIntegerField(default=0, help_text='Bumped each time an issued PO is re-opened and amended.'),
        ),
        migrations.CreateModel(
            name='PurchaseOrderRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveSmallIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_revisions', to=settings.AUTH_USER_MODEL)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='procurement.purchaseorder')),
            ],
            options={
                'ordering': ['-revision', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('QUOTATION', 'Quotation'), ('PO_PDF', 'Purchase Order PDF'), ('DELIVERY_NOTE', 'Delivery Note'), ('INVOICE', 'Invoice'), ('INSPECTION', 'Inspection Report'), ('OTHER', 'Other')], default='OTHER', max_length=16)),
                ('file', models.FileField(upload_to='attachments/')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='procurement_content_1cebea_idx')],
            },
        ),
    ]
