# Generated by Django 5.2.12 on 2026-07-12 15:46

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('procurement', '0006_purchaseorder_emailed_at_purchaseorder_revision_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_on_hand', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=16)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='procurement.material')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_items', to='procurement.project')),
            ],
            options={
                'ordering': ['project', 'material'],
                'constraints': [models.UniqueConstraint(fields=('material', 'project'), name='unique_stock_item')],
            },
        ),
        migrations.CreateModel(
            name='StockLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movement', models.CharField(choices=[('RECEIPT', 'Goods Receipt'), ('RETURN', 'Purchase Return'), ('ISSUE', 'Issue / Consumption'), ('ADJUSTMENT', 'Adjustment / Reversal')], max_length=12)),
                ('quantity', models.DecimalField(decimal_places=3, help_text='Signed movement: positive increases stock, negative decreases it.', max_digits=16)),
                ('balance_after', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=16)),
                ('remarks', models.CharField(blank=True, max_length=255)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='procurement.material')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='procurement.project')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['material', 'project'], name='procurement_materia_b78b08_idx')],
            },
        ),
    ]
