# Generated by Django 5.2.12 on 2026-07-12 16:26

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0010_purchasereturn_purchasereturnline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('contract_type', models.CharField(choices=[('BLANKET', 'Blanket Order'), ('RATE', 'Rate Contract'), ('SERVICE', 'Service Agreement')], default='BLANKET', max_length=10)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('EXPIRED', 'Expired'), ('TERMINATED', 'Terminated'), ('RENEWED', 'Renewed')], default='DRAFT', max_length=12)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Ceiling value of the blanket order (0 = uncapped).', max_digits=16)),
                ('consumed_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('auto_renew', models.BooleanField(default=False)),
                ('terms', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to=settings.AUTH_USER_MODEL)),
                ('renewed_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renewals', to='procurement.purchasecontract')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='procurement.vendor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContractLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5)),
                ('max_quantity', models.DecimalField(blank=True, decimal_places=3, help_text='Optional cap on the quantity that may be ordered under this contract.', max_digits=14, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='procurement.material')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.purchasecontract')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='procurement.purchasecontract'),
        ),
    ]
